# (text, sender, expected) expected: "scam" -> must be medium/high; "high" -> must be high; "safe" -> must be low
SCAMS = [
 "Grandma its me Jake. I got arrested in Cancun and need $3000 for bail. Dont tell mom, wire it via Western Union please.",
 "Hi Papa, I lost my phone and this is a friend's. I'm in the hospital after an accident, need $1,500 in Google Play cards, please don't tell Dad.",
 "This is Agent Miller from the IRS. You owe $4,812 in back taxes. Pay today with gift cards or you will be arrested.",
 "SSA: Your Social Security number was used in a crime in Texas. Your benefits are suspended. Call 1-844-555-0101 immediately.",
 "Medicare notice: new plastic card being issued. Confirm your Medicare number and date of birth now to avoid losing coverage.",
 "Windows Security Alert!! Your PC is infected with 3 viruses. Call Microsoft Support 1-888-555-0120. Do not shut down.",
 "Apple Support: your iCloud was breached. Call our certified technician at 1-866-555-0177 to remove the hackers remotely.",
 "Hello my dear, I am Sgt. Williams stationed in Kabul. I need $700 for leave papers so I can come marry you. Send by Bitcoin.",
 "My love, I am stuck at the port and need $2,000 customs fee for the gold shipment. You are the only one I trust, tell no one.",
 "Invest $5000 in our crypto trading group. Guaranteed 40% weekly returns, zero risk. Message me on WhatsApp now.",
 "Pre-IPO opportunity! Double your money in 30 days guaranteed. Wire funds today, spots are limited.",
 "CONGRATULATIONS! You've won the $1,000,000 Mega Sweepstakes. Pay a $300 processing fee with iTunes cards to claim your prize.",
 "You are our lucky winner of a Walmart $750 gift card. Claim here: bit.ly/walm-win before it expires today.",
 "Amazon: suspicious charge of $899.99 on your account. Call 1-877-555-0190 now to cancel this order and get a refund.",
 "PayPal: your account is limited. Verify your identity at paypal-secure-check.xyz within 24 hours or it will be closed.",
 "Chase Alert: your card was locked due to fraud. Click https://chase-secure-login.top/unlock to verify your info.",
 "USPS: your parcel is held, unpaid $1.99 shipping fee. Pay at usps-parcel-fee.online to release it today.",
 "FedEx: delivery failed. Reschedule and pay a small customs fee here: fedex-reship.info/pay",
 "Your Netflix account is on hold. Update your payment info at netflix-billing-help.click to avoid cancellation.",
 "Work from home, earn $400 a day, no experience needed. Text your name, address and bank info to start your paid trial.",
 "I'm your new pastor. Stuck in a meeting, can't call. Please buy 5 Apple cards for a sick member and text me the codes. Keep it private.",
 "Are you free? I need a favor. Buy Google Play cards worth $500 and send me the redemption codes. I'm in a meeting.",
 "Help! I've been kidnapped. They want $10,000 in Bitcoin or they'll hurt me. Don't call the police!",
 "Your electricity will be cut off in 30 minutes unless you pay $340 now by Zelle. Call 1-855-555-0133.",
 "Final notice: legal action will be filed against you. Call our office immediately to settle your unpaid balance of $1,900.",
 "Hello this is Norton. Your subscription renewed for $449.99. Call 1-833-555-0166 to cancel and refund.",
 "Your Social Security payment will stop unless you confirm your bank account number and SSN by replying to this text.",
 "Dear customer, your bank account has been temporarily frozen. Log in to verify your identity: http://192.168.10.4/bank",
 "Google here! We need remote access to your computer to fix your account. Please download AnyDesk and read us the code.",
 "Lottery board of Spain: you have won 2.5 million euros. Send your full name, address and a processing fee of $250 to claim.",
]
SAFE = [
 "Hi Mom, I'll be there around 6 for dinner. Need me to bring anything?",
 "Grandma, happy birthday! We love you. Call you tonight after dinner.",
 "Your appointment with Dr. Chen is tomorrow at 10:30 AM. Reply C to confirm or call the office to reschedule.",
 "Your prescription is ready for pickup at Walgreens. Reply STOP to opt out.",
 "Reminder: your annual wellness visit is next Tuesday at 2 PM. Please bring your insurance card.",
 "Chase: a purchase of $23.10 at Trader Joe's was made on your card ending 5521. If this wasn't you, call the number on the back of your card.",
 "Your verification code is 771204. Don't share it with anyone.",
 "Your Amazon order has shipped and will arrive Wednesday. Track it in the app.",
 "Your USPS package will arrive today. Track it at tools.usps.com.",
 "Your electric bill of $96.40 is due Oct 15. Autopay is on, no action needed.",
 "Thanks for your payment of $54.00. Your account is current. Your next statement will be available on the 1st.",
 "The library has your hold ready for pickup. It will be held until Saturday.",
 "Hey Dad, I sent the photos here: https://photos.google.com/share/xyz123. Let me know which you like.",
 "Here's the recipe: https://www.allrecipes.com/recipe/10813/best-chocolate-chip-cookies/ Enjoy!",
 "Your Medicare Part D open enrollment begins October 15. Learn more at medicare.gov.",
 "Your Social Security statement is ready. Sign in at ssa.gov to view it.",
 "Security alert: a new sign-in to your Google Account on a Mac. If this was you, no action is needed.",
 "You're receiving this email because you signed up for our newsletter. You can unsubscribe at any time.",
 "Your flight to Denver leaves at 7:45 AM Friday. Check in on the airline app starting tomorrow.",
 "Winter storm warning tonight. Stay off the roads if possible. - County Emergency Services",
 "Can you pick up milk on the way home? Thanks!",
 "Church potluck is Sunday at noon. Bring a dish to share!",
 "Your Netflix payment of $15.49 was processed. No action is needed.",
 "Your dental cleaning is scheduled for Monday at 9 AM at Oakwood Dental. Please call if you need to reschedule.",
 "Zoom meeting starts in 10 minutes: https://zoom.us/j/8842217755",
 "Great seeing you yesterday! Let's do lunch again next week.",
 "Your car is ready for pickup at the service center. Total due at pickup is $210.",
 "Verizon: your bill is ready. Amount due $88.20 on Oct 3. View it in the My Verizon app.",
 "Bank of America: your statement is ready. We'll never ask for your password by text.",
 "The pharmacy will close early today at 5 PM for the holiday.",
]
SENDER_CASES = [  # (text, sender, must_be_at_least, description)
 ("Your statement is ready.", "alerts@chase-secure-help.com", "medium"),
 ("Your statement is ready.", "no-reply@paypa1.com", "medium"),
 ("Your statement is ready.", "alerts@chase.com", "low"),
 ("This is the IRS. You owe taxes.", "irs.helpdesk@gmail.com", "high"),
]
